### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by DougMaier** [DougMaier/codelab-js-intro#1]
Hey @egillespie, can you take a look at this? It's [hosted here](http://wakeful-wind.surge.sh) and meets the following [project](http://lansingcodelab.com/lessons/js-intro/1) criteria:
- [x] Include [a button](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Example) that will display a silly, but tasteful joke in an alert when clicked
- [x] Return no errors (warnings are OK) when the HTML is uploaded to the [W3C Markup Validation Service](http://validator.w3.org/#validate_by_upload)
- [x] Return no errors or warnings when the JavaScript is pasted into [JavaScript Lint](http://www.javascriptlint.com/online_lint.php)

**Comment by egillespie** [comment]
Hi Doug, I think a couple of small changes are needed to meet the project criteria:
1. The joke should be presented using a JavaScript `alert()` instead of changing the HTML on the page.
2. Semicolons should be at the end of the second and third lines of your JavaScript. The comment says they can be ignored, which is true, but as you write more JavaScript, those missing semicolons will come back to bite you. Building the habit of putting them at the end of all statements now will avoid a lot of frustration in the future.

Make those changes and add a comment here when you're done (make sure to @egillespie mention me) and I'll give it another once over.

Thanks!

**Comment by DougMaier** [comment]
@egillespie  I've followed up on all of your suggestions.  Let me know what you think of the changes.

**Comment by egillespie** [comment]
Looks great! :shipit: 

You don't have to hang onto old code in comments if you don't want to. Git, your version control, will take care of saving those old bits of code for you! :)

**Comment by DougMaier** [comment]
@egillespie I left the old code in there more as a note to myself than as a way of retaining the old code.
Thanks for the squirrel.  On to the next exercise!
